### ISSUE TITLE
Unable to find image 'localhost/nextcloud:27.1.4-apache-customized' locally 

### ISSUE THREAD

**Issue by Carsten3000** [mother-of-all-self-hosting/mash-playbook#127]
I am running just install-all on a fresh Ubuntu 22.04 (ARM)

I am getting this error for nextcloud:

```bash
failed: [XXX.de] (item={'name': 'mash-nextcloud-server.service', 'priority': 2000, 'groups': ['mash', 'nextcloud', 'nextcloud-server']}) => changed=false 
  ansible_loop_var: item
  item:
    groups:
    - mash
    - nextcloud
    - nextcloud-server
    name: mash-nextcloud-server.service
    priority: 2000
  msg: |-
    Unable to start service mash-nextcloud-server.service: Job for mash-nextcloud-server.service failed because the control process exited with error code.
    See "systemctl status mash-nextcloud-server.service" and "journalctl -xeu mash-nextcloud-server.service" for details.
```

The image is downloaded.
`nextcloud                                       27.1.4-apache     4ffe31245259   11 days ago    1.21GB`

The journalctl log:

```bash
Dec 10 15:55:46 ubuntu-4gb-nbg1-2 systemd[1]: mash-nextcloud-server.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ An ExecStartPre= process belonging to unit mash-nextcloud-server.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Dec 10 15:55:46 ubuntu-4gb-nbg1-2 systemd[1]: mash-nextcloud-server.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit mash-nextcloud-server.service has entered the 'failed' state with result 'exit-code'.
Dec 10 15:55:46 ubuntu-4gb-nbg1-2 systemd[1]: Failed to start Nextcloud Server (mash-nextcloud-server).
░░ Subject: A start job for unit mash-nextcloud-server.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit mash-nextcloud-server.service has finished with a failure.
░░ 
░░ The job identifier is 4659 and the job result is failed.
...skipping...
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A stop job for unit mash-nextcloud-server.service has finished.
░░ 
░░ The job identifier is 4659 and the job result is done.
Dec 10 15:55:46 ubuntu-4gb-nbg1-2 systemd[1]: Starting Nextcloud Server (mash-nextcloud-server)...
░░ Subject: A start job for unit mash-nextcloud-server.service has begun execution
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit mash-nextcloud-server.service has begun execution.
░░ 
░░ The job identifier is 4659.
Dec 10 15:55:46 ubuntu-4gb-nbg1-2 mash-nextcloud-server[8901]: Unable to find image 'localhost/nextcloud:27.1.4-apache-customized' locally
Dec 10 15:55:46 ubuntu-4gb-nbg1-2 mash-nextcloud-server[8901]: Error response from daemon: error parsing HTTP 404 response body: invalid character 'p' after top-level value: "404 page not found\n"
Dec 10 15:55:46 ubuntu-4gb-nbg1-2 systemd[1]: mash-nextcloud-server.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ An ExecStartPre= process belonging to unit mash-nextcloud-server.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Dec 10 15:55:46 ubuntu-4gb-nbg1-2 systemd[1]: mash-nextcloud-server.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit mash-nextcloud-server.service has entered the 'failed' state with result 'exit-code'.
Dec 10 15:55:46 ubuntu-4gb-nbg1-2 systemd[1]: Failed to start Nextcloud Server (mash-nextcloud-server).
░░ Subject: A start job for unit mash-nextcloud-server.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit mash-nextcloud-server.service has finished with a failure.
░░ 
░░ The job identifier is 4659 and the job result is failed.
```

I dont have the parameter nextcloud_container_image_customized set.  I don't know why the script would want to use a customized container. Any idea?

**Comment by spantaleev** [comment]
Is it you who reported this in our Matrix room the other day?

----

You could try debugging a few things.

First, SSH into the server and delete the `/mash/nextcloud/customized-container-src` directory, if it exists.

First, do a normal run: `just install-service nextcloud` and observe if the `Ensure customizations Dockerfile is created` task is reported as `ok`, `changed` or `skipping`.

If customizations are not enabled (and they shouldn't be for you), it should say `skipping`.

You could also verify that no customized container image is being built by checking if `/mash/nextcloud/customized-container-src` exists now (remember, you were supposed to ensure this directory is deleted before running `just install-service nextcloud`). If the path doesn't exist, it's what we expect.

You could also try deleting the systemd service file on the server (`/etc/systemd/system/mash-nextcloud-server.service`) and running `just install-service nextcloud` again to ensure it's being recreated. Check which container image is mentioned inside - it should be `docker.io/nextcloud:27.1.4-apache`, not `localhost/nextcloud:27.1.4-apache-customized`.

If you see the correct image (`docker.io/nextcloud:27.1.4-apache`), but restarting services via the playbook keeps trying to use the customized image, perhaps you had customizations enabled at some point before and the service was using a customized image. systemd may not be taking new systemd service definitions into account. The playbook is supposed to reload systemd as part of running the `start` tag, but may be failing to do so for some reason. You could try running `systemctl daemon-reload` yourself.

------

Here's more debugging advice, which involves editing the Nextcloud Ansible role.

Try editing `roles/galaxy/nextcloud/tasks/install.yml`. Add the following at the top (below the `---` line):

```yml
- debug: var="nextcloud_container_image_customizations_enabled"
- debug: var="nextcloud_container_image_customizations_php_imagick_installation_enabled"
- debug: var="nextcloud_container_image_customizations_samba_enabled"
- debug: var="nextcloud_container_image_customizations_packages_to_install"
- debug: var="nextcloud_container_image_final"
- debug: var="nextcloud_container_image"
- fail: msg="Stop here"
```

Then run the playbook again (`just install-service nextcloud`) and see what it reports.

It should say:
1. `false`
2. `false`
3. `false`
4. `[]`
5. `docker.io/nextcloud:27.1.4-apache`
6. `docker.io/nextcloud:27.1.4-apache`

----

Your problem may also be caused by an old or faulty Ansible or Jinja version, which interprets the `nextcloud_container_image_customizations_enabled` definition in `roles/galaxy/nextcloud/defaults/main.yml` incorrectly.

Try making it use a single-line YAML string. Edit `roles/galaxy/nextcloud/defaults/main.yml`  as shown below:

```diff
+nextcloud_container_image_customizations_enabled: "{{ nextcloud_container_image_customizations_php_imagick_installation_enabled or nextcloud_container_image_customizations_samba_enabled or nextcloud_container_image_customizations_packages_to_install | length > 0 }}
-nextcloud_container_image_customizations_enabled: |
-  {{
-    (
-      nextcloud_container_image_customizations_php_imagick_installation_enabled
-      or
-      nextcloud_container_image_customizations_samba_enabled
-      or
-      nextcloud_container_image_customizations_packages_to_install | length > 0
-    )
-  }}
```

The, run a real installation or try the `debug: var=..` checks and see if you get a different result.

**Comment by Carsten3000** [comment]
Thank you for your detailed answer, it was on point as it was your last suggestion, my local software was outdated.

I did not report this on matrix.

**Comment by spantaleev** [comment]
Is it all working as expected now after updating your software (Ansible / Jinja)?

**Comment by Carsten3000** [comment]
Hey, sorry for the belated answer, everything works fine.
