### ISSUE TITLE
Migrate away from Redis?

### ISSUE THREAD

**Issue by Beryesa** [mother-of-all-self-hosting/mash-playbook#175]
So, Redis is [no longer](https://lwn.net/Articles/966133/) open source https://redis.com/blog/redis-adopts-dual-source-available-licensing/
Can we consider migrating to a fork or alternative? Maybe [keyDB](https://github.com/Snapchat/KeyDB)?
Do you have any futher plans?
Thank you!

**Comment by spantaleev** [comment]
Yes, we already have a [KeyDB role](https://github.com/mother-of-all-self-hosting/ansible-role-keydb) and since today is being used in [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy). See [(Backward Compatibility Break) The playbook now defaults to KeyDB, instead of Redis](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/17b109d9f67d8a1b6e18bfc197cc7eb80e5ce8f6/CHANGELOG.md#backward-compatibility-break-the-playbook-now-defaults-to-keydb-instead-of-redis).

The KeyDB role hasn't been integrated into mash-playbook yet, but should be soon enough.

**Comment by Beryesa** [comment]
Thank you :heart_decoration:
