### ISSUE TITLE
Rocky Linux 9.1 support

### ISSUE THREAD

**Issue by jahanson** [mother-of-all-self-hosting/mash-playbook#4]
I was able to install docker on Rocky Linux 9.1 by:

1. adding the centos `docker-ce` repo
2. enabling `epel-release` to install `python3-docker`
3. disabling `timesyncd` in the vars.yml and opting for `chronyd` that's already installed.

_add_prereqs.sh_
```sh
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo dnf install epel-release -y
sudo dnf install python3-docker -y
```
_vars.yml_
```yml
devture_timesync_installation_enabled: false
```

**Comment by spantaleev** [comment]
I've just migrated my installation (with various services running on the same server - Gitea, Netxtcloud. Miniflux, etc.) from Rocky Linux 8 to Rocky Linux 9.

I started with a fresh minimal installation (from an `.iso`) of Rocky Linux 9, using a default playbook configuration:

- Docker installation and Docker SDK for Python installation is enabled by default. It's [enabled by default in the example vars.yml file](https://github.com/mother-of-all-self-hosting/mash-playbook/blob/6951fff78f59fa4101a215d61c06ed50dee661c3/examples/vars.yml#L23-L45), so unless you explicitly disable it, you should be fine.
- the Docker SDK for Python installation, powered by the [com.devture.ansible.role.docker_sdk_for_python](https://github.com/devture/com.devture.ansible.role.docker_sdk_for_python) Ansible role [automatically installs `epel-release`](https://github.com/devture/com.devture.ansible.role.docker_sdk_for_python/blob/129c8590e106b83e6f4c259649a613c6279e937a/tasks/setup_redhat.yml) on RedHat 8 and newer, so you should be fine.
- I don't see `chrony` installed by default on my Rocky Linux 9 minimal installation. systemd is part of the default installation though, so using `systemd-timesyncd` makes sense. On Rocky Linux 9, it's part of a separate `systemd-timesyncd`. On some distros (Archlinux), `timesyncd` is even part of the default `systemd` package, so it's available by default.

I have however hit some problems with Gitea, Vaultwarden and Woodpecker CI agent/server roles trying to mount `/etc/timezone` into the containers. Rocky Linux 9 does not seem to have such a file, so these services were failing.

I have fixed them up in e8cc892 and it all runs smoothly.

-----

To summarize, I'm using a default minimal Rocky Linux 9 installation and baring the minor timezone bugs I hit (and fixed in e8cc892), everything worked smoothly without any manual fixups.

I suspect that you:

- explicitly disabled Docker installation (via `mash_playbook_docker_installation_enabled: false`) and then had to install Docker manually
- explicitly disabled Docker SDK for Python installation (via `devture_docker_sdk_for_python_installation_enabled: false`) and then had to install it manually. The Ansible role installs `epel-release` and `python3-docker`, just like you've done manually.

Were you confused by the wording here? https://github.com/mother-of-all-self-hosting/mash-playbook/blob/6951fff78f59fa4101a215d61c06ed50dee661c3/examples/vars.yml#L23-L45

----

As for the timesync stuff, I'm not sure why you decided to use `chrony`, but.. it's OK. We don't insist on forcing `systemd-timesyncd` on you.

Perhaps enabling NTP during the Rocky Linux installation process (there was some checkbox from what I remember) automatically installs `chrony`?

**Comment by jahanson** [comment]
I should've added more about my environment and a little more about exactly why these changes were necessary.
I am creating a rocky 9.1 VM on Azure. Maybe it goes against the spirit of this book as it leans to self hosting but I had some free credits to test it out and needed a quick nextcloud instance. So I thought I'd try this new mash repo.

1. The mash script failed to install docker because 'docker-ce' was not found. Enabling the repo and re-running ansible installed docker fine for me and allowed it to proceed.
2. The script would get stuck and file on the 10th attempt of 'ensuring postgress image is pulled' if I did not manually enable epel and `dnf install python3-docker`. It gave me an error along the lines of python docker not found.
3. The Azure image provided by Rocky Linux uses dev device to communicate with the hypervisor for ntp communication and is included in that image by default. Installing timesyncd simply failed with an error when trying by default. Disabling it was a requirement for me to get the script running again.

I said I got the script running but nextcloud was left in a broken state. I tried to investigate further why but ran out of time. Nginx/apache (not sure) was just providing a 404 but traefik provided a valid cert just fine.

**Comment by spantaleev** [comment]
> No package docker-ce available.

It seems like for some reason, the docker role (we use [geerlingguy/ansible-role-docker](https://github.com/geerlingguy/ansible-role-docker) did not correctly add `docker-ce`.

----

The Docker SDK for Python role should have enabled `epel-release` and installed `python3-docker`. If it didn't do that, then it probably did not consider you to be running a `RedHat` distro here:

https://github.com/devture/com.devture.ansible.role.docker_sdk_for_python/blob/129c8590e106b83e6f4c259649a613c6279e937a/tasks/main.yml#L6-L8

Are you sure you're running Rocky Linux and not some weird rebranded and unrecorgnizable (by Ansible) Azure spin-off?

-----

We're fine with self-hosting on VPS servers provided by others ("in the cloud"). In fact, at [etke.cc](https://etke.cc), we're hosting many many such servers on various VPS providers.

I suppose the problem stems from what Microsoft is doing with this "Rocky Linux" installation. If you tell us more, we may be able to find a solution.

**Comment by jahanson** [comment]
The author of the image is 'The Rocky Enterprise Software Foundation Inc' 

The output of /etc/os-release is:
```
NAME="Rocky Linux"
VERSION="9.1 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.1 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.1"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
```
Is there some other way you're determining the version/distro?

This is the image i'm using: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/erockyenterprisesoftwarefoundationinc1653071250513.rockylinux-9?tab=Overview

**Comment by jahanson** [comment]
I pulled the ansible variables you're using.

```
PLAY [all] ***********************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************
[WARNING]: Platform linux on host nextcloud.example.com is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python
interpreter could change the meaning of that path. See https://docs.ansible.com/ansible/2.10/reference_appendices/interpreter_discovery.html for more information.
ok: [nextcloud.example.com]

TASK [Distribution] **************************************************************************************************************************************************
ok: [nextcloud.example.com] => {
    "msg": "Rocky"
}

TASK [Distribution version] ******************************************************************************************************************************************
ok: [nextcloud.example.com] => {
    "msg": "9.1"
}

TASK [Distribution major version] ************************************************************************************************************************************
ok: [nextcloud.example.com] => {
    "msg": "9"
}

PLAY RECAP ***********************************************************************************************************************************************************
nextcloud.example.com         : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by spantaleev** [comment]
`ansible_os_family` is still `RedHat`, isn't it?

Makes me wonder why the Docker SDK for Python did not get [installed](https://github.com/devture/com.devture.ansible.role.docker_sdk_for_python/blob/129c8590e106b83e6f4c259649a613c6279e937a/tasks/main.yml#L6-L8)?

**Comment by jahanson** [comment]
Just checked `ansible_os_family` and it looks like it's `Rocky` .  I guess a few things got skipped over since this was not the expected os family.

**Comment by spantaleev** [comment]
It seems to be `RedHat` for my Rocky Linux 9.1 installation (installed from ISO).

I suppose it's:

- either Ansible doing something else for you (where and how do you run Ansible? Have you tried running Ansible in a container, as [described here](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/ansible.md#using-ansible-via-docker))
- or, this Rocky Linux image on Azure is somehow different and Ansible determins `ansible_os_family` differently for it

**Comment by jahanson** [comment]
I have a local installed VM running the iso provided directly from rocky linux and I got the same ansible facts with `ansible 2.10.8` & `ansible-playbook 2.10.8` (this is the most up to date version on ubuntu 22.04)

However, using the docker image provided (`ansible:2.13.6-r0`) in the link I get: 
Weird.
```
TASK [Distribution] **************************************************************************************************************************************************************************
ok: [nextcloud.example.com] => {
    "msg": "Rocky"
}

TASK [Distribution] **************************************************************************************************************************************************************************
ok: [nextcloud.example.com] => {
    "msg": "RedHat"
}

TASK [Distribution version] ******************************************************************************************************************************************************************
ok: [nextcloud.example.com] => {
    "msg": "9.1"
}

TASK [Distribution major version] ************************************************************************************************************************************************************
ok: [nextcloud.example.com] => {
    "msg": "9"
}
```

**Comment by spantaleev** [comment]
One of these says `RedHat` now. You've labelled both `Distribution`, so I'm not sure what it is.

Seems different though?

**Comment by jahanson** [comment]
Yes, sorry I was a little ambiguous there. 

`2.13.6-r0` now shows `RedHat` for `ansible_os_family` and `2.10.8` does not.

**Comment by spantaleev** [comment]
Sounds like Ansible on Ubuntu is being buggy as always. That's not surprising - I've seen many many causes of it causing trouble and not being updated despite there being Trackpad issues with many people complaining. "LTS" really means nothing. Ubuntu is crap.

You may have better luck installing Ansible from a PPA, or running Ansible (or anything you care about) in a container. Ideally, you'd switch to a better distro - either something Arch-based, or latest Fedora or that SUSE Tumbleweed rolling distro.

**Comment by jahanson** [comment]
What a mess. Yeah, not a fan. For one reason or another my laptop needs windows so I use wsl2. It's the only ubuntu I run... I suppose I can switch that to rocky or fedora I just didn't really think about it. Thank you for you time, I really appreciate you helping me find the root issue here!

**Comment by spantaleev** [comment]
I think there's also a way to run Ansible on Windows directly? Not sure how well that works.

-----

I suppose you can't really run Ansible in a container on that Ubuntu (under WSL2), because.. there's no real Linux kernel around? Or does the WSL2 stuff run in a real Linux VM now? I'm not sure.

**Comment by jahanson** [comment]
I can't find any way to install it on windows. But yeah, WSL2 has a tighter integration now. You run Docker Desktop and there's a socket that links between the two.. Probably just do the container method it seems more reliable especially with these playbooks.
