### ISSUE TITLE
Support for external PostgreSQL?

### ISSUE THREAD

**Issue by perfectra1n** [mother-of-all-self-hosting/mash-playbook#56]
Hey all,

Thanks for the great playbook, it looks great, and the documentation is solid as well. Are there any plans to be able to support an external PostgreSQL server? Currently I'm running an external instance, and would love to be able to use it. 

For example, I'm able to provide database variables to the Nextcloud playbook via `nextcloud_database_*` variables, but unfortunately they don't do anything with the `devture_postgres*` disabled. 

Borg also references an external Postgres server, but it just 404s.
https://github.com/mother-of-all-self-hosting/mash-playbook/blob/7338b0b8ca6d53026c53dcbd10fd10a5e00c161e/docs/services/backup-borg.md?plain=1#L11

**Comment by spantaleev** [comment]
There shouldn't be a problem with using an external Postgres server for the various services.

Roles are auto-configured to use the integrated servers. This configuration is added to `group_vars/mash_servers`. You can find the relevant variables for the service you care about, copy it to your `vars.yml` and adjust it to point to your external server.

Using the integrated database is easiest, because the playbook auto-creates databases and credentials for each service that you enable. If you're using your own external database, you need to take care of this part by yourself.

----

backup-borg will only automatically backup the integrated database servers.

When using your own external database, it won't be backed up automatically. You can point backup-borg to it manually, as described in our [updated documentation](https://github.com/mother-of-all-self-hosting/mash-playbook/commit/4eb71df91a44bef4a36c36483e1d37813ed54152).
