### ISSUE TITLE
mash-playbook not integrating with matrix-traeffik

### ISSUE THREAD

**Issue by thomsbe** [mother-of-all-self-hosting/mash-playbook#73]
I have the matrix-playbook with traeffik, fronted by a Caddy2. I'm trying to let the mash-playbook use the traeffik from the matrix-playbook. I got a lot of log-lines from matrix-treaffik right after the start and both subdomains running into a 404 not found.

```
Jun 24 10:13:52 tbaer.de matrix-traefik[2976747]: time="2023-06-24T08:13:52Z" level=error msg="the router mash-gitea@docker uses a non-existent resolver: default"
Jun 24 10:13:52 tbaer.de matrix-traefik[2976747]: time="2023-06-24T08:13:52Z" level=error msg="the router mash-uptime-kuma@docker uses a non-existent resolver: default"
Jun 24 10:14:21 tbaer.de matrix-traefik[2976747]: time="2023-06-24T08:14:21Z" level=error msg="entryPoint \"web-secure\" doesn't exist" routerName=mash-gitea@docker entryPointName=web-secure
Jun 24 10:14:21 tbaer.de matrix-traefik[2976747]: time="2023-06-24T08:14:21Z" level=error msg="no valid entryPoint for this router" routerName=mash-gitea@docker
Jun 24 10:14:21 tbaer.de matrix-traefik[2976747]: time="2023-06-24T08:14:21Z" level=error msg="entryPoint \"web-secure\" doesn't exist" entryPointName=web-secure routerName=mash-uptime-kuma@docker
Jun 24 10:14:21 tbaer.de matrix-traefik[2976747]: time="2023-06-24T08:14:21Z" level=error msg="no valid entryPoint for this router" routerName=mash-uptime-kuma@docker
Jun 24 10:14:21 tbaer.de matrix-traefik[2976747]: time="2023-06-24T08:14:21Z" level=error msg="entryPoint \"web-secure\" doesn't exist" entryPointName=web-secure routerName=mash-gitea@docker
Jun 24 10:14:21 tbaer.de matrix-traefik[2976747]: time="2023-06-24T08:14:21Z" level=error msg="no valid entryPoint for this router" routerName=mash-gitea@docker
Jun 24 10:14:21 tbaer.de matrix-traefik[2976747]: time="2023-06-24T08:14:21Z" level=error msg="entryPoint \"web-secure\" doesn't exist" routerName=mash-uptime-kuma@docker entryPointName=web-secure
Jun 24 10:14:21 tbaer.de matrix-traefik[2976747]: time="2023-06-24T08:14:21Z" level=error msg="no valid entryPoint for this router" routerName=mash-uptime-kuma@docker
Jun 24 10:14:21 tbaer.de matrix-traefik[2976747]: time="2023-06-24T08:14:21Z" level=error msg="the router mash-gitea@docker uses a non-existent resolver: default"
Jun 24 10:14:21 tbaer.de matrix-traefik[2976747]: time="2023-06-24T08:14:21Z" level=error msg="the router mash-uptime-kuma@docker uses a non-existent resolver: default"
```

mash-playbook config:
```
mash_playbook_reverse_proxy_type: other-traefik-container
mash_playbook_reverse_proxyable_services_additional_network: traefik
```

Everything looks ok, but I guess, I have missed some config somewhere or there is a issue.

**Comment by spantaleev** [comment]
Yours is a special case because you're putting other reverse-proxies in front of Traefik.

Given that you're fronting Traefik (`matrix-traefik`) with another webserver, you may wish to migrate over some of the additional Traefik settings you're using for `matrix-docker-ansible-deploy`, as described in [Fronting the integrated reverse-proxy webserver with another reverse-proxy](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md#fronting-the-integrated-reverse-proxy-webserver-with-another-reverse-proxy)  of the `matrix-docker-ansible-deploy` documentation.

You probably need this added to `vars.yml` on the mash-playbook side:

```yml
devture_traefik_config_entrypoint_web_secure_enabled: false
```

This would automatically cascade into:

- switching `devture_traefik_entrypoint_primary` to default to the `devture_traefik_config_entrypoint_web_name` entrypoint (=`web`), instead of using the non-existent `web-secure` entrypoint

- switching `devture_traefik_config_certificatesResolvers_acme_enabled` to `false`, so cert resolvers would not be added to any services

**Comment by thomsbe** [comment]
Tanks a lot! This was the missing piece. Now it's working.
